### ISSUE TITLE
Issues with PHP 7

### ISSUE THREAD

**Issue by codeartisticninja** [Bravehartk2/dokuwiki-piwik2#2]
This plugin doesn't seem to work well with PHP 7.. Can this be fixed..?

I get these warnings:

Warning: Declaration of action_plugin_piwik2::register(&$controller) should be compatible with DokuWiki_Action_Plugin::register(Doku_Event_Handler $controller) in /home/www/the.codeartistic.ninja/learns/lib/plugins/piwik2/action.php on line 29

Warning: Cannot modify header information - headers already sent by (output started at /home/www/the.codeartistic.ninja/learns/lib/plugins/piwik2/action.php:29) in /home/www/the.codeartistic.ninja/learns/inc/actions.php on line 210

Warning: Cannot modify header information - headers already sent by (output started at /home/www/the.codeartistic.ninja/learns/lib/plugins/piwik2/action.php:29) in /home/www/the.codeartistic.ninja/learns/lib/tpl/dokuwiki/main.php on line 12

**Comment by Bravehartk2** [comment]
Hallo,
I added a fix for that to the new release:
https://github.com/Bravehartk2/dokuwiki-piwik2/releases/tag/ElenorofTsort-2016-06-26a-php7

Thanks for your hint.

**Comment by codeartisticninja** [comment]
Awesome! thanks! :)
